In [3]:
# Importamos las librerías necesarias
import pandas as pd
import numpy as np
pd.set_option("display.max_columns", None)
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
# Para imputación de nulos usando métodos estadísticos avanzados
from sklearn.impute import SimpleImputer 
from sklearn.experimental import enable_iterative_imputer # Necesario para IterativeImputer
from sklearn.impute import IterativeImputer 
from sklearn.impute import KNNImputer

In [5]:
df_hr = pd.read_csv("hr.csv")
df_hr.head(5)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41.0,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,sALES eXECUTIVE,4.0,Single,5993.0,19479,8,Y,Yes,11,3,1,80.0,0,8,0.0,1,6,4,0,5.0
1,49.0,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,3,Male,61,2,2,rESEARCH sCIENTIST,2.0,Married,5130.0,24907,1,Y,No,23,4,4,NaN,1,10,3.0,3,10,7,1,7.0
2,37.0,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,4,Male,92,2,1,lABORATORY tECHNICIAN,3.0,Single,2090.0,2396,6,Y,Yes,15,3,2,NaN,0,7,3.0,3,0,0,0,0.0
3,33.0,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,4,Female,56,3,1,rESEARCH sCIENTIST,3.0,Married,2909.0,23159,1,Y,Yes,11,3,3,80.0,0,8,3.0,3,8,7,3,0.0
4,27.0,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,1,Male,40,3,1,lABORATORY tECHNICIAN,2.0,Married,3468.0,16632,9,Y,No,12,3,4,80.0,1,6,3.0,3,2,2,2,2.0

In [6]:
def exploracion_basica(df):
    print(f"Las dos primeras filas son:")
    display(df.head(2))
    print("=" * 50)
    print(f"Las dos últimas filas son:")
    display(df.tail(2))
    print("=" * 50)
    print(f"Las dos filas aleatorias son:")
    display(df.sample(2)) 
    print("=" * 50)
    print(f"Información sobre DataFrame:")
    print(df.info())
    print("=" * 50)
    print(f"El dataframe tiene {df.shape[0]} filas y {df.shape[1]} columnas.")
    return df

In [7]:
df_hr = exploracion_basica(df_hr)

Las dos primeras filas son:

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41.0,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,sALES eXECUTIVE,4.0,Single,5993.0,19479,8,Y,Yes,11,3,1,80.0,0,8,0.0,1,6,4,0,5.0
1,49.0,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,3,Male,61,2,2,rESEARCH sCIENTIST,2.0,Married,5130.0,24907,1,Y,No,23,4,4,NaN,1,10,3.0,3,10,7,1,7.0

==================================================
Las dos últimas filas son:

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
1472,24.0,Yes,Travel_Rarely,240,Human Resources,22,1,Human Resources,1,1714,4,Male,58,1,1,hUMAN rESOURCES,3.0,Married,1555.0,11585,1,Y,No,11,3,3,80.0,1,1,2.0,3,1,0,0,0.0
1473,45.0,No,Travel_Rarely,1339,Research & Development,7,3,Life Sciences,1,86,2,Male,59,3,3,rESEARCH sCIENTIST,1.0,Divorced,9724.0,18787,2,Y,No,17,3,3,NaN,1,25,2.0,3,1,0,0,0.0

==================================================
Las dos filas aleatorias son:

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
739,27.0,No,Travel_Rarely,1055,Research & Development,2,4,Life Sciences,1,1027,1,Female,47,3,2,mANUFACTURING dIRECTOR,4.0,Married,4227.0,4658,0,Y,No,18,3,2,80.0,1,4,2.0,3,3,2,2,2.0
874,30.0,No,Travel_Rarely,853,Research & Development,7,4,Life Sciences,1,1224,3,Male,49,3,2,lABORATORY tECHNICIAN,3.0,NaN,3491.0,11309,1,Y,No,13,3,1,80.0,3,10,4.0,2,10,7,8,9.0

==================================================
Información sobre DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1474 entries, 0 to 1473
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1401 non-null   float64
 1   Attrition                 1474 non-null   object
 2   BusinessTravel            1357 non-null   object
 3   DailyRate                 1474 non-null   int64
 4   Department                1445 non-null   object
 5   DistanceFromHome          1474 non-null   int64
 6   Education                 1474 non-null   int64
 7   EducationField            1416 non-null   object
 8   EmployeeCount             1474 non-null   int64
 9   EmployeeNumber            1474 non-null   int64
 10  EnvironmentSatisfaction   1474 non-null   int64
 11  Gender                    1474 non-null   object
 12  HourlyRate                1474 non-null   int64
 13  JobInvolvement            1474 non-null   int64
 14  JobLevel                  1474 non-null   int64
 15  JobRole                   1474 non-null   object
 16  JobSatisfaction           1445 non-null   float64
 17  MaritalStatus             1342 non-null   object
 18  MonthlyIncome             1460 non-null   float64
 19  MonthlyRate               1474 non-null   int64
 20  NumCompaniesWorked        1474 non-null   int64
 21  Over18                    1474 non-null   object
 22  OverTime                  1430 non-null   object
 23  PercentSalaryHike         1474 non-null   int64
 24  PerformanceRating         1474 non-null   int64
 25  RelationshipSatisfaction  1474 non-null   int64
 26  StandardHours             1310 non-null   float64
 27  StockOptionLevel          1474 non-null   int64
 28  TotalWorkingYears         1474 non-null   int64
 29  TrainingTimesLastYear     1386 non-null   float64
 30  WorkLifeBalance           1474 non-null   int64
 31  YearsAtCompany            1474 non-null   int64
 32  YearsInCurrentRole        1474 non-null   int64
 33  YearsSinceLastPromotion   1474 non-null   int64
 34  YearsWithCurrManager      1326 non-null   float64
dtypes: float64(6), int64(20), object(9)
memory usage: 403.2+ KB
None
==================================================
El dataframe tiene 1474 filas y 35 columnas.

In [8]:
df_hr.sample(5)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
167,30.0,No,Travel_Rarely,1339,Sales,5,3,Life Sciences,1,228,2,Female,41,3,3,sALES eXECUTIVE,4.0,Marreid,9419.0,8053,2,Y,No,12,3,3,80.0,1,12,2.0,3,10,9,7,4.0
1286,40.0,No,Travel_Rarely,616,Research & Development,2,2,Life Sciences,1,1802,3,Female,99,3,1,lABORATORY tECHNICIAN,1.0,NaN,3377.0,25605,4,Y,No,17,3,4,80.0,1,7,5.0,2,4,3,0,2.0
486,37.0,No,Travel_Rarely,558,Sales,2,3,Marketing,1,656,4,Male,75,3,2,sALES eXECUTIVE,3.0,Married,9602.0,3010,4,Y,Yes,11,3,3,80.0,1,17,3.0,2,3,0,1,0.0
765,38.0,No,Travel_Frequently,1186,Research & Development,3,4,Other,1,1060,3,Male,44,3,1,rESEARCH sCIENTIST,3.0,Married,2821.0,2997,3,Y,No,16,3,1,80.0,1,8,2.0,3,2,2,2,2.0
119,43.0,No,Travel_Frequently,394,Sales,26,2,Life Sciences,1,158,3,Male,92,3,4,mANAGER,4.0,NaN,16959.0,19494,1,Y,Yes,12,3,4,80.0,2,25,3.0,4,25,12,4,12.0

In [9]:
# añadir _ a los nombres de las columnas y poner en minúscula

df_hr.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [ ]:
import re  #importar regex para insertar guines bajsos antes de mayúsculas internas. Buena práctica
#r'(?<!^)(?=[A-Z])' significa “encuentra cada mayúscula que no esté al inicio, y pon un _ antes”.


df_hr.columns = (
    df_hr.columns
      .str.replace(r'(?<!^)(?=[A-Z])', '_', regex=True)  # Inserta _ antes de mayúsculas internas
      .str.lower()                                       # Convierte a minúsculas
)

In [11]:
df_hr.columns

Index(['age', 'attrition', 'business_travel', 'daily_rate', 'department',
       'distance_from_home', 'education', 'education_field', 'employee_count',
       'employee_number', 'environment_satisfaction', 'gender', 'hourly_rate',
       'job_involvement', 'job_level', 'job_role', 'job_satisfaction',
       'marital_status', 'monthly_income', 'monthly_rate',
       'num_companies_worked', 'over18', 'over_time', 'percent_salary_hike',
       'performance_rating', 'relationship_satisfaction', 'standard_hours',
       'stock_option_level', 'total_working_years', 'training_times_last_year',
       'work_life_balance', 'years_at_company', 'years_in_current_role',
       'years_since_last_promotion', 'years_with_curr_manager'],
      dtype='object')

In [14]:
df_hr.rename(columns={'over18': 'over_18'}, inplace=True)
df_hr.head(2)

,age,attrition,business_travel,daily_rate,department,distance_from_home,education,education_field,employee_count,employee_number,environment_satisfaction,gender,hourly_rate,job_involvement,job_level,job_role,job_satisfaction,marital_status,monthly_income,monthly_rate,num_companies_worked,over_18,over_time,percent_salary_hike,performance_rating,relationship_satisfaction,standard_hours,stock_option_level,total_working_years,training_times_last_year,work_life_balance,years_at_company,years_in_current_role,years_since_last_promotion,years_with_curr_manager
0,41.0,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,sALES eXECUTIVE,4.0,Single,5993.0,19479,8,Y,Yes,11,3,1,80.0,0,8,0.0,1,6,4,0,5.0
1,49.0,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,3,Male,61,2,2,rESEARCH sCIENTIST,2.0,Married,5130.0,24907,1,Y,No,23,4,4,NaN,1,10,3.0,3,10,7,1,7.0

In [15]:
# cambair edad a int

columna_edad_a_int = ['age']

for col in columna_edad_a_int:
    df_hr[col] = df_hr[col].astype('Int64')

df_hr[columna_edad_a_int].dtypes

age    Int64
dtype: object

In [18]:
df_hr['job_role'].unique()

array([' sALES eXECUTIVE ', ' rESEARCH sCIENTIST ',
       ' lABORATORY tECHNICIAN ', ' mANUFACTURING dIRECTOR ',
       ' hEALTHCARE rEPRESENTATIVE ', ' mANAGER ',
       ' sALES rEPRESENTATIVE ', ' rESEARCH dIRECTOR ',
       ' hUMAN rESOURCES '], dtype=object)

In [21]:
df_hr['job_role'] = df_hr['job_role'].str.strip().str.lower().str.replace(r'\s+', '_', regex=True)
df_hr.head(2)

,age,attrition,business_travel,daily_rate,department,distance_from_home,education,education_field,employee_count,employee_number,environment_satisfaction,gender,hourly_rate,job_involvement,job_level,job_role,job_satisfaction,marital_status,monthly_income,monthly_rate,num_companies_worked,over_18,over_time,percent_salary_hike,performance_rating,relationship_satisfaction,standard_hours,stock_option_level,total_working_years,training_times_last_year,work_life_balance,years_at_company,years_in_current_role,years_since_last_promotion,years_with_curr_manager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,sales_executive,4.0,Single,5993.0,19479,8,Y,Yes,11,3,1,80.0,0,8,0.0,1,6,4,0,5.0
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,3,Male,61,2,2,research_scientist,2.0,Married,5130.0,24907,1,Y,No,23,4,4,NaN,1,10,3.0,3,10,7,1,7.0

In [23]:
df_hr['business_travel'].unique()

array(['Travel_Rarely', 'Travel_Frequently', 'Non-Travel', nan],
      dtype=object)

In [25]:
df_hr['business_travel'].value_counts(dropna=False)

business_travel
Travel_Rarely        955
Travel_Frequently    263
Non-Travel           139
NaN                  117
Name: count, dtype: int64

In [27]:
# 1. cambiar nombre de categorias: 

nuevas_categorias_business_travel = {
    'Travel_Rarely': 'rarely',
    'Travel_Frequently': 'frequently',
    'Non-Travel': 'non_travel'}

In [28]:
# aplicar el reemplazo
df_hr['business_travel'] = df_hr['business_travel'].replace(nuevas_categorias_business_travel)

In [29]:
# comprobar

df_hr.head(2)

,age,attrition,business_travel,daily_rate,department,distance_from_home,education,education_field,employee_count,employee_number,environment_satisfaction,gender,hourly_rate,job_involvement,job_level,job_role,job_satisfaction,marital_status,monthly_income,monthly_rate,num_companies_worked,over_18,over_time,percent_salary_hike,performance_rating,relationship_satisfaction,standard_hours,stock_option_level,total_working_years,training_times_last_year,work_life_balance,years_at_company,years_in_current_role,years_since_last_promotion,years_with_curr_manager
0,41,Yes,rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,sales_executive,4.0,Single,5993.0,19479,8,Y,Yes,11,3,1,80.0,0,8,0.0,1,6,4,0,5.0
1,49,No,frequently,279,Research & Development,8,1,Life Sciences,1,2,3,Male,61,2,2,research_scientist,2.0,Married,5130.0,24907,1,Y,No,23,4,4,NaN,1,10,3.0,3,10,7,1,7.0

In [30]:
df_hr['department'].unique()

array(['Sales', 'Research & Development', nan, 'Human Resources'],
      dtype=object)

In [31]:
df_hr['department'] = df_hr['department'].str.strip().str.lower().str.replace(r'\s+', '_', regex=True)

In [32]:
df_hr['department'].unique()

array(['sales', 'research_&_development', nan, 'human_resources'],
      dtype=object)

In [33]:
df_hr['marital_status'].unique()

array(['Single', 'Married', 'Divorced', nan, 'Marreid'], dtype=object)

In [34]:
df_hr['marital_status'] = df_hr['marital_status'].str.strip().str.lower().str.replace(r'\s+', '_', regex=True)

In [35]:
df_hr['marital_status'].unique()

array(['single', 'married', 'divorced', nan, 'marreid'], dtype=object)

In [36]:
nuevas_categorias_marital_status = {
    'single': 'single',
    'married': 'married',
    'divorced': 'divorced',
    'marreid': 'married'
    }

In [37]:
# aplicar el reemplazo
df_hr['marital_status'] = df_hr['marital_status'].replace(nuevas_categorias_marital_status)

In [40]:
df_hr.sample(5)

,age,attrition,business_travel,daily_rate,department,distance_from_home,education,education_field,employee_count,employee_number,environment_satisfaction,gender,hourly_rate,job_involvement,job_level,job_role,job_satisfaction,marital_status,monthly_income,monthly_rate,num_companies_worked,over_18,over_time,percent_salary_hike,performance_rating,relationship_satisfaction,standard_hours,stock_option_level,total_working_years,training_times_last_year,work_life_balance,years_at_company,years_in_current_role,years_since_last_promotion,years_with_curr_manager
1204,<NA>,Yes,frequently,708,sales,7,2,Medical,1,1691,4,Female,95,3,1,sales_representative,3.0,NaN,2655.0,11740,2,Y,Yes,11,3,3,80.0,2,19,3.0,3,9,7,7,7.0
515,35,No,non_travel,727,research_&_development,3,3,Life Sciences,1,704,3,Male,41,2,1,laboratory_technician,3.0,married,1281.0,16900,1,Y,No,18,3,3,80.0,2,1,3.0,3,1,0,0,0.0
1083,40,Yes,rarely,676,research_&_development,9,4,Life Sciences,1,1534,4,Male,86,3,1,laboratory_technician,1.0,single,2018.0,21831,3,Y,No,14,3,2,80.0,0,15,3.0,1,5,4,1,0.0
986,39,No,rarely,1498,sales,21,4,Life Sciences,1,1390,1,Male,44,2,2,sales_executive,4.0,married,6120.0,3567,3,Y,Yes,12,3,4,80.0,2,8,2.0,4,5,4,1,4.0
274,21,No,NaN,996,research_&_development,3,2,Medical,1,379,4,Male,100,2,1,research_scientist,3.0,single,3230.0,10531,1,Y,No,17,3,1,80.0,0,3,4.0,4,3,2,1,0.0

In [38]:
df_hr.dtypes

age                             Int64
attrition                      object
business_travel                object
daily_rate                      int64
department                     object
distance_from_home              int64
education                       int64
education_field                object
employee_count                  int64
employee_number                 int64
environment_satisfaction        int64
gender                         object
hourly_rate                     int64
job_involvement                 int64
job_level                       int64
job_role                       object
job_satisfaction              float64
marital_status                 object
monthly_income                float64
monthly_rate                    int64
num_companies_worked            int64
over_18                        object
over_time                      object
percent_salary_hike             int64
performance_rating              int64
relationship_satisfaction       int64
standard_hours                float64
stock_option_level              int64
total_working_years             int64
training_times_last_year      float64
work_life_balance               int64
years_at_company                int64
years_in_current_role           int64
years_since_last_promotion      int64
years_with_curr_manager       float64
dtype: object

In [42]:
df_hr['education_field'].unique()

array(['Life Sciences', 'Other', 'Medical', nan, 'Marketing',
       'Technical Degree', 'Human Resources'], dtype=object)

In [43]:
df_hr['education_field'] = df_hr['education_field'].str.strip().str.lower().str.replace(r'\s+', '_', regex=True)

In [44]:
df_hr['education_field'].unique()

array(['life_sciences', 'other', 'medical', nan, 'marketing',
       'technical_degree', 'human_resources'], dtype=object)

In [45]:
df_hr = df_hr.drop(columns=['employee_count'])

In [46]:
df_hr['gender'].unique()

array(['Female', 'Male'], dtype=object)

In [47]:
df_hr['over_18'].unique()

array(['Y'], dtype=object)

In [48]:
print(df_hr.duplicated().sum())

4

In [49]:
mascara_duplicados_hr = df_hr.duplicated(keep=False)
mascara_duplicados_hr

0       False
1       False
2       False
3       False
4       False
        ...
1469    False
1470     True
1471     True
1472     True
1473     True
Length: 1474, dtype: bool

In [50]:
df_hr[mascara_duplicados_hr].sort_values(by="employee_number")

,age,attrition,business_travel,daily_rate,department,distance_from_home,education,education_field,employee_number,environment_satisfaction,gender,hourly_rate,job_involvement,job_level,job_role,job_satisfaction,marital_status,monthly_income,monthly_rate,num_companies_worked,over_18,over_time,percent_salary_hike,performance_rating,relationship_satisfaction,standard_hours,stock_option_level,total_working_years,training_times_last_year,work_life_balance,years_at_company,years_in_current_role,years_since_last_promotion,years_with_curr_manager
67,45,No,rarely,1339,research_&_development,7,3,life_sciences,86,2,Male,59,3,3,research_scientist,1.0,divorced,9724.0,18787,2,Y,No,17,3,3,NaN,1,25,2.0,3,1,0,0,0.0
1473,45,No,rarely,1339,research_&_development,7,3,life_sciences,86,2,Male,59,3,3,research_scientist,1.0,divorced,9724.0,18787,2,Y,No,17,3,3,NaN,1,25,2.0,3,1,0,0,0.0
1471,53,No,rarely,1084,research_&_development,13,2,medical,250,4,Female,57,4,2,manufacturing_director,1.0,divorced,4450.0,26250,1,Y,No,11,3,3,NaN,2,5,3.0,3,4,2,1,3.0
184,53,No,rarely,1084,research_&_development,13,2,medical,250,4,Female,57,4,2,manufacturing_director,1.0,divorced,4450.0,26250,1,Y,No,11,3,3,NaN,2,5,3.0,3,4,2,1,3.0
1470,28,No,rarely,866,sales,5,3,medical,1469,4,Male,84,3,2,sales_executive,1.0,single,8463.0,23490,0,Y,No,18,3,4,NaN,0,6,4.0,3,5,4,1,NaN
1041,28,No,rarely,866,sales,5,3,medical,1469,4,Male,84,3,2,sales_executive,1.0,single,8463.0,23490,0,Y,No,18,3,4,NaN,0,6,4.0,3,5,4,1,NaN
1222,24,Yes,rarely,240,human_resources,22,1,human_resources,1714,4,Male,58,1,1,human_resources,3.0,married,1555.0,11585,1,Y,No,11,3,3,80.0,1,1,2.0,3,1,0,0,0.0
1472,24,Yes,rarely,240,human_resources,22,1,human_resources,1714,4,Male,58,1,1,human_resources,3.0,married,1555.0,11585,1,Y,No,11,3,3,80.0,1,1,2.0,3,1,0,0,0.0

In [51]:
df_hr.drop_duplicates(inplace=True)
print(df_hr.duplicated().sum())

0

In [52]:
print(df_hr.isnull().sum())

age                            73
attrition                       0
business_travel               117
daily_rate                      0
department                     29
distance_from_home              0
education                       0
education_field                58
employee_number                 0
environment_satisfaction        0
gender                          0
hourly_rate                     0
job_involvement                 0
job_level                       0
job_role                        0
job_satisfaction               29
marital_status                132
monthly_income                 14
monthly_rate                    0
num_companies_worked            0
over_18                         0
over_time                      44
percent_salary_hike             0
performance_rating              0
relationship_satisfaction       0
standard_hours                161
stock_option_level              0
total_working_years             0
training_times_last_year       88
work_life_balance               0
years_at_company                0
years_in_current_role           0
years_since_last_promotion      0
years_with_curr_manager       147
dtype: int64

In [ ]:
nulos_hr = (df_hr.isnull().mean() * 100)

# Filtrar solo columnas con nulos
nulos_hr = nulos_hr[nulos_hr > 0]

# Convertir a dataframe
nulos_hr = nulos_hr.reset_index()

nulos_hr.rename(columns={"index": "nombre_columna", 0: "%_nulos"}, inplace=True)

nulos_hr

              nombre_columna    %_nulos
0                        age   4.965986
1            business_travel   7.959184
2                 department   1.972789
3            education_field   3.945578
4           job_satisfaction   1.972789
5             marital_status   8.979592
6             monthly_income   0.952381
7                  over_time   2.993197
8             standard_hours  10.952381
9   training_times_last_year   5.986395
10   years_with_curr_manager  10.000000

In [63]:
df_hr['standard_hours'].unique()

array([80., nan])

**<u>revision para limpieza</u>**


**<u>hecho:</u>**

- nombre de columnas en minuscula y separado con _ ✔️
- edad cambiar a int ✔️ 
- job role: cambiar a todo en minusculas ✔️ 
- bussines travel lo dejaria solo con rarely o con frequantly. (quitar travel).✔️ 
- departament: poner en minusculas ✔️ 
- marital status hay singled, maried, divorced, escribir homogeneo ✔️
- eliminar columna employee count ✔️
- education_field categorias en minuscula y separado con _ ✔️
- eliminar duplicados ✔️
- ver cuantos nulos tenemos ✔️




**<u>falta:</u>**
- gestion de nulos



**<u>Decidir si eliminamos:</u>**

- monthly rate

- daily rate

- over_18 (solo un valor: Y. todos mayores de edad)

- standard hours: solo tiene valor 80 o nulos, creo que noe s relevante esta columna ( copiado de IA: En la mayoría de datasets de RRHH (incluyendo los clásicos de IBM), esta columna: siempre vale 80. representa 80 horas por periodo de pago quincenal. equivale a 40 horas semanales. Es decir, no mide las horas reales trabajadas, sino el estándar contractual.) --> esto confirma que la podemos eliminar.

- education field no se si es relevante. igual podemos ver si las personas que se fueron tenian puestos de trabajo relacionados con sus estudios