In [1]:
# Importamos las librerías necesarias
import pandas as pd
import numpy as np
pd.set_option("display.max_columns", None)
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
# Para imputación de nulos usando métodos estadísticos avanzados
from sklearn.impute import SimpleImputer 
from sklearn.experimental import enable_iterative_imputer # Necesario para IterativeImputer
from sklearn.impute import IterativeImputer 
from sklearn.impute import KNNImputer

FASE 1 - ANÁLISIS EXPLORATORIO INICIAL:
Homogenización columnas
Limpieza datos
Gestión datos nulos

In [3]:
df_hr = pd.read_csv("hr.csv")
df_hr.head(2)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41.0,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,sALES eXECUTIVE,4.0,Single,5993.0,19479,8,Y,Yes,11,3,1,80.0,0,8,0.0,1,6,4,0,5.0
1,49.0,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,3,Male,61,2,2,rESEARCH sCIENTIST,2.0,Married,5130.0,24907,1,Y,No,23,4,4,NaN,1,10,3.0,3,10,7,1,7.0

In [4]:
def exploracion_basica(df):
    print(f"Las dos primeras filas son:")
    display(df.head(2))
    print("=" * 50)
    print(f"Las dos últimas filas son:")
    display(df.tail(2))
    print("=" * 50)
    print(f"Las dos filas aleatorias son:")
    display(df.sample(2)) 
    print("=" * 50)
    print(f"Información sobre DataFrame:")
    print(df.info())
    print("=" * 50)
    print(f"El dataframe tiene {df.shape[0]} filas y {df.shape[1]} columnas.")
    return df

In [5]:
df_hr = exploracion_basica(df_hr)

Las dos primeras filas son:

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41.0,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,sALES eXECUTIVE,4.0,Single,5993.0,19479,8,Y,Yes,11,3,1,80.0,0,8,0.0,1,6,4,0,5.0
1,49.0,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,3,Male,61,2,2,rESEARCH sCIENTIST,2.0,Married,5130.0,24907,1,Y,No,23,4,4,NaN,1,10,3.0,3,10,7,1,7.0

==================================================
Las dos últimas filas son:

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
1472,24.0,Yes,Travel_Rarely,240,Human Resources,22,1,Human Resources,1,1714,4,Male,58,1,1,hUMAN rESOURCES,3.0,Married,1555.0,11585,1,Y,No,11,3,3,80.0,1,1,2.0,3,1,0,0,0.0
1473,45.0,No,Travel_Rarely,1339,Research & Development,7,3,Life Sciences,1,86,2,Male,59,3,3,rESEARCH sCIENTIST,1.0,Divorced,9724.0,18787,2,Y,No,17,3,3,NaN,1,25,2.0,3,1,0,0,0.0

==================================================
Las dos filas aleatorias son:

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
563,25.0,No,Travel_Rarely,883,Sales,26,1,NaN,1,781,3,Female,32,3,2,sALES eXECUTIVE,4.0,Single,6180.0,22807,1,Y,No,23,4,2,80.0,0,6,5.0,2,6,5,1,NaN
322,32.0,No,Travel_Rarely,1018,Research & Development,2,4,Medical,1,439,1,Female,74,4,2,rESEARCH sCIENTIST,4.0,NaN,5055.0,10557,7,Y,No,16,3,3,NaN,0,10,0.0,2,7,7,0,7.0

==================================================
Información sobre DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1474 entries, 0 to 1473
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1401 non-null   float64
 1   Attrition                 1474 non-null   object
 2   BusinessTravel            1357 non-null   object
 3   DailyRate                 1474 non-null   int64
 4   Department                1445 non-null   object
 5   DistanceFromHome          1474 non-null   int64
 6   Education                 1474 non-null   int64
 7   EducationField            1416 non-null   object
 8   EmployeeCount             1474 non-null   int64
 9   EmployeeNumber            1474 non-null   int64
 10  EnvironmentSatisfaction   1474 non-null   int64
 11  Gender                    1474 non-null   object
 12  HourlyRate                1474 non-null   int64
 13  JobInvolvement            1474 non-null   int64
 14  JobLevel                  1474 non-null   int64
 15  JobRole                   1474 non-null   object
 16  JobSatisfaction           1445 non-null   float64
 17  MaritalStatus             1342 non-null   object
 18  MonthlyIncome             1460 non-null   float64
 19  MonthlyRate               1474 non-null   int64
 20  NumCompaniesWorked        1474 non-null   int64
 21  Over18                    1474 non-null   object
 22  OverTime                  1430 non-null   object
 23  PercentSalaryHike         1474 non-null   int64
 24  PerformanceRating         1474 non-null   int64
 25  RelationshipSatisfaction  1474 non-null   int64
 26  StandardHours             1310 non-null   float64
 27  StockOptionLevel          1474 non-null   int64
 28  TotalWorkingYears         1474 non-null   int64
 29  TrainingTimesLastYear     1386 non-null   float64
 30  WorkLifeBalance           1474 non-null   int64
 31  YearsAtCompany            1474 non-null   int64
 32  YearsInCurrentRole        1474 non-null   int64
 33  YearsSinceLastPromotion   1474 non-null   int64
 34  YearsWithCurrManager      1326 non-null   float64
dtypes: float64(6), int64(20), object(9)
memory usage: 403.2+ KB
None
==================================================
El dataframe tiene 1474 filas y 35 columnas.

In [6]:
df_hr.sample(2)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
438,35.0,No,NaN,1276,Research & Development,16,3,Life Sciences,1,586,4,Male,72,3,3,hEALTHCARE rEPRESENTATIVE,3.0,Married,7632.0,14295,4,Y,Yes,12,3,3,NaN,0,10,NaN,3,8,7,0,0.0
44,30.0,No,Travel_Frequently,721,Research & Development,1,2,Medical,1,57,3,Female,58,3,2,lABORATORY tECHNICIAN,4.0,Single,4011.0,10781,1,Y,No,23,4,4,80.0,0,12,2.0,3,12,8,3,7.0

In [7]:
# añadir _ a los nombres de las columnas y poner en minúscula

df_hr.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [8]:
import re  #importar regex para insertar guines bajsos antes de mayúsculas internas. Buena práctica
#r'(?<!^)(?=[A-Z])' significa “encuentra cada mayúscula que no esté al inicio, y pon un _ antes”.


df_hr.columns = (
    df_hr.columns
    # 1. Inserta _ entre minúscula y Mayúscula (ej. MonthlyIncome -> Monthly_Income)
    .str.replace(r'([a-z])([A-Z])', r'\1_\2', regex=True)
    # 2. Inserta _ entre una letra y el primer número que encuentre (ej. Over18 -> Over_18)
    .str.replace(r'([a-zA-Z])([0-9])', r'\1_\2', regex=True)
    # 3. Convierte todo a minúsculas
    .str.lower()
)

In [9]:
df_hr.rename(columns={'over18': 'over_18'}, inplace=True)
df_hr.head(2)

,age,attrition,business_travel,daily_rate,department,distance_from_home,education,education_field,employee_count,employee_number,environment_satisfaction,gender,hourly_rate,job_involvement,job_level,job_role,job_satisfaction,marital_status,monthly_income,monthly_rate,num_companies_worked,over_18,over_time,percent_salary_hike,performance_rating,relationship_satisfaction,standard_hours,stock_option_level,total_working_years,training_times_last_year,work_life_balance,years_at_company,years_in_current_role,years_since_last_promotion,years_with_curr_manager
0,41.0,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,sALES eXECUTIVE,4.0,Single,5993.0,19479,8,Y,Yes,11,3,1,80.0,0,8,0.0,1,6,4,0,5.0
1,49.0,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,3,Male,61,2,2,rESEARCH sCIENTIST,2.0,Married,5130.0,24907,1,Y,No,23,4,4,NaN,1,10,3.0,3,10,7,1,7.0

In [10]:
# cambair edad a int

columna_edad_a_int = ['age']

for col in columna_edad_a_int:
    df_hr[col] = df_hr[col].astype('Int64')

df_hr[columna_edad_a_int].dtypes

age    Int64
dtype: object

In [11]:
df_hr['job_role'].unique()

array([' sALES eXECUTIVE ', ' rESEARCH sCIENTIST ',
       ' lABORATORY tECHNICIAN ', ' mANUFACTURING dIRECTOR ',
       ' hEALTHCARE rEPRESENTATIVE ', ' mANAGER ',
       ' sALES rEPRESENTATIVE ', ' rESEARCH dIRECTOR ',
       ' hUMAN rESOURCES '], dtype=object)

In [12]:
df_hr['job_role'] = df_hr['job_role'].str.strip().str.lower().str.replace(r'\s+', '_', regex=True)
df_hr.head(2)

,age,attrition,business_travel,daily_rate,department,distance_from_home,education,education_field,employee_count,employee_number,environment_satisfaction,gender,hourly_rate,job_involvement,job_level,job_role,job_satisfaction,marital_status,monthly_income,monthly_rate,num_companies_worked,over_18,over_time,percent_salary_hike,performance_rating,relationship_satisfaction,standard_hours,stock_option_level,total_working_years,training_times_last_year,work_life_balance,years_at_company,years_in_current_role,years_since_last_promotion,years_with_curr_manager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,sales_executive,4.0,Single,5993.0,19479,8,Y,Yes,11,3,1,80.0,0,8,0.0,1,6,4,0,5.0
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,3,Male,61,2,2,research_scientist,2.0,Married,5130.0,24907,1,Y,No,23,4,4,NaN,1,10,3.0,3,10,7,1,7.0

In [13]:
df_hr['business_travel'].unique()

array(['Travel_Rarely', 'Travel_Frequently', 'Non-Travel', nan],
      dtype=object)

In [14]:
df_hr['business_travel'].value_counts(dropna=False)

business_travel
Travel_Rarely        955
Travel_Frequently    263
Non-Travel           139
NaN                  117
Name: count, dtype: int64

In [15]:
# 1. cambiar nombre de categorias: 

nuevas_categorias_business_travel = {
    'Travel_Rarely': 'rarely',
    'Travel_Frequently': 'frequently',
    'Non-Travel': 'non_travel'}

In [16]:
# aplicar el reemplazo
df_hr['business_travel'] = df_hr['business_travel'].replace(nuevas_categorias_business_travel)

In [17]:
# comprobar

df_hr.head(2)

,age,attrition,business_travel,daily_rate,department,distance_from_home,education,education_field,employee_count,employee_number,environment_satisfaction,gender,hourly_rate,job_involvement,job_level,job_role,job_satisfaction,marital_status,monthly_income,monthly_rate,num_companies_worked,over_18,over_time,percent_salary_hike,performance_rating,relationship_satisfaction,standard_hours,stock_option_level,total_working_years,training_times_last_year,work_life_balance,years_at_company,years_in_current_role,years_since_last_promotion,years_with_curr_manager
0,41,Yes,rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,sales_executive,4.0,Single,5993.0,19479,8,Y,Yes,11,3,1,80.0,0,8,0.0,1,6,4,0,5.0
1,49,No,frequently,279,Research & Development,8,1,Life Sciences,1,2,3,Male,61,2,2,research_scientist,2.0,Married,5130.0,24907,1,Y,No,23,4,4,NaN,1,10,3.0,3,10,7,1,7.0

In [18]:
df_hr['department'].unique()

array(['Sales', 'Research & Development', nan, 'Human Resources'],
      dtype=object)

In [19]:
df_hr['department'] = df_hr['department'].str.strip().str.lower().str.replace(r'\s+', '_', regex=True)

In [20]:
df_hr['department'].unique()

array(['sales', 'research_&_development', nan, 'human_resources'],
      dtype=object)

In [21]:
df_hr['marital_status'].unique()

array(['Single', 'Married', 'Divorced', nan, 'Marreid'], dtype=object)

In [22]:
df_hr['marital_status'] = df_hr['marital_status'].str.strip().str.lower().str.replace(r'\s+', '_', regex=True)

In [23]:
df_hr['marital_status'].unique()

array(['single', 'married', 'divorced', nan, 'marreid'], dtype=object)

In [24]:
nuevas_categorias_marital_status = {
    'single': 'single',
    'married': 'married',
    'divorced': 'divorced',
    'marreid': 'married'
    }

In [25]:
# aplicar el reemplazo
df_hr['marital_status'] = df_hr['marital_status'].replace(nuevas_categorias_marital_status)

In [26]:
df_hr.sample(5)

,age,attrition,business_travel,daily_rate,department,distance_from_home,education,education_field,employee_count,employee_number,environment_satisfaction,gender,hourly_rate,job_involvement,job_level,job_role,job_satisfaction,marital_status,monthly_income,monthly_rate,num_companies_worked,over_18,over_time,percent_salary_hike,performance_rating,relationship_satisfaction,standard_hours,stock_option_level,total_working_years,training_times_last_year,work_life_balance,years_at_company,years_in_current_role,years_since_last_promotion,years_with_curr_manager
861,46,No,rarely,1402,sales,2,3,NaN,1,1204,3,Female,69,3,4,manager,1.0,NaN,17048.0,24097,8,Y,No,23,4,1,80.0,0,28,2.0,3,26,15,15,NaN
657,29,No,rarely,1086,research_&_development,7,1,Medical,1,912,1,Female,62,2,1,laboratory_technician,4.0,divorced,2532.0,6054,6,Y,No,14,3,3,80.0,3,8,5.0,3,4,3,0,3.0
1353,34,Yes,non_travel,967,NaN,16,4,Technical Degree,1,1905,4,Male,85,1,1,research_scientist,1.0,NaN,2307.0,14460,1,Y,Yes,23,4,2,80.0,1,5,2.0,3,5,2,3,0.0
56,35,No,frequently,853,sales,18,5,Life Sciences,1,74,2,Male,71,3,3,sales_executive,1.0,married,9069.0,11031,1,Y,No,22,4,4,80.0,1,9,3.0,2,9,8,1,8.0
1065,55,No,NaN,1229,research_&_development,4,4,Life Sciences,1,1501,4,Male,30,3,2,healthcare_representative,NaN,NaN,4035.0,16143,0,Y,Yes,16,3,2,NaN,0,4,NaN,3,3,2,1,2.0

In [27]:
df_hr.dtypes

age                             Int64
attrition                      object
business_travel                object
daily_rate                      int64
department                     object
distance_from_home              int64
education                       int64
education_field                object
employee_count                  int64
employee_number                 int64
environment_satisfaction        int64
gender                         object
hourly_rate                     int64
job_involvement                 int64
job_level                       int64
job_role                       object
job_satisfaction              float64
marital_status                 object
monthly_income                float64
monthly_rate                    int64
num_companies_worked            int64
over_18                        object
over_time                      object
percent_salary_hike             int64
performance_rating              int64
relationship_satisfaction       int64
standard_hours                float64
stock_option_level              int64
total_working_years             int64
training_times_last_year      float64
work_life_balance               int64
years_at_company                int64
years_in_current_role           int64
years_since_last_promotion      int64
years_with_curr_manager       float64
dtype: object

In [28]:
df_hr['education_field'].unique()

array(['Life Sciences', 'Other', 'Medical', nan, 'Marketing',
       'Technical Degree', 'Human Resources'], dtype=object)

In [29]:
df_hr['education_field'] = df_hr['education_field'].str.strip().str.lower().str.replace(r'\s+', '_', regex=True)

In [30]:
df_hr['education_field'].unique()

array(['life_sciences', 'other', 'medical', nan, 'marketing',
       'technical_degree', 'human_resources'], dtype=object)

In [31]:
df_hr.columns

Index(['age', 'attrition', 'business_travel', 'daily_rate', 'department',
       'distance_from_home', 'education', 'education_field', 'employee_count',
       'employee_number', 'environment_satisfaction', 'gender', 'hourly_rate',
       'job_involvement', 'job_level', 'job_role', 'job_satisfaction',
       'marital_status', 'monthly_income', 'monthly_rate',
       'num_companies_worked', 'over_18', 'over_time', 'percent_salary_hike',
       'performance_rating', 'relationship_satisfaction', 'standard_hours',
       'stock_option_level', 'total_working_years', 'training_times_last_year',
       'work_life_balance', 'years_at_company', 'years_in_current_role',
       'years_since_last_promotion', 'years_with_curr_manager'],
      dtype='object')

In [32]:
df_hr['standard_hours'].unique()

array([80., nan])

In [33]:
df_hr['over_18'].unique()

array(['Y'], dtype=object)

In [34]:
# Eliminamos columnas que no aportan información relevante para el análisis o modelado
df_hr = df_hr.drop(columns=['employee_count', 'over_18', 'standard_hours', 'monthly_rate', 'daily_rate'], errors='ignore')

In [35]:
df_hr.head(2)

,age,attrition,business_travel,department,distance_from_home,education,education_field,employee_number,environment_satisfaction,gender,hourly_rate,job_involvement,job_level,job_role,job_satisfaction,marital_status,monthly_income,num_companies_worked,over_time,percent_salary_hike,performance_rating,relationship_satisfaction,stock_option_level,total_working_years,training_times_last_year,work_life_balance,years_at_company,years_in_current_role,years_since_last_promotion,years_with_curr_manager
0,41,Yes,rarely,sales,1,2,life_sciences,1,2,Female,94,3,2,sales_executive,4.0,single,5993.0,8,Yes,11,3,1,0,8,0.0,1,6,4,0,5.0
1,49,No,frequently,research_&_development,8,1,life_sciences,2,3,Male,61,2,2,research_scientist,2.0,married,5130.0,1,No,23,4,4,1,10,3.0,3,10,7,1,7.0

In [36]:
df_hr['gender'].unique()

array(['Female', 'Male'], dtype=object)

In [37]:
print(df_hr.duplicated().sum())

4

In [38]:
mascara_duplicados_hr = df_hr.duplicated(keep=False)
mascara_duplicados_hr

0       False
1       False
2       False
3       False
4       False
        ...
1469    False
1470     True
1471     True
1472     True
1473     True
Length: 1474, dtype: bool

In [39]:
df_hr[mascara_duplicados_hr].sort_values(by="employee_number")

,age,attrition,business_travel,department,distance_from_home,education,education_field,employee_number,environment_satisfaction,gender,hourly_rate,job_involvement,job_level,job_role,job_satisfaction,marital_status,monthly_income,num_companies_worked,over_time,percent_salary_hike,performance_rating,relationship_satisfaction,stock_option_level,total_working_years,training_times_last_year,work_life_balance,years_at_company,years_in_current_role,years_since_last_promotion,years_with_curr_manager
67,45,No,rarely,research_&_development,7,3,life_sciences,86,2,Male,59,3,3,research_scientist,1.0,divorced,9724.0,2,No,17,3,3,1,25,2.0,3,1,0,0,0.0
1473,45,No,rarely,research_&_development,7,3,life_sciences,86,2,Male,59,3,3,research_scientist,1.0,divorced,9724.0,2,No,17,3,3,1,25,2.0,3,1,0,0,0.0
1471,53,No,rarely,research_&_development,13,2,medical,250,4,Female,57,4,2,manufacturing_director,1.0,divorced,4450.0,1,No,11,3,3,2,5,3.0,3,4,2,1,3.0
184,53,No,rarely,research_&_development,13,2,medical,250,4,Female,57,4,2,manufacturing_director,1.0,divorced,4450.0,1,No,11,3,3,2,5,3.0,3,4,2,1,3.0
1470,28,No,rarely,sales,5,3,medical,1469,4,Male,84,3,2,sales_executive,1.0,single,8463.0,0,No,18,3,4,0,6,4.0,3,5,4,1,NaN
1041,28,No,rarely,sales,5,3,medical,1469,4,Male,84,3,2,sales_executive,1.0,single,8463.0,0,No,18,3,4,0,6,4.0,3,5,4,1,NaN
1222,24,Yes,rarely,human_resources,22,1,human_resources,1714,4,Male,58,1,1,human_resources,3.0,married,1555.0,1,No,11,3,3,1,1,2.0,3,1,0,0,0.0
1472,24,Yes,rarely,human_resources,22,1,human_resources,1714,4,Male,58,1,1,human_resources,3.0,married,1555.0,1,No,11,3,3,1,1,2.0,3,1,0,0,0.0

In [40]:
df_hr['attrition'].value_counts()

attrition
No     1236
Yes     238
Name: count, dtype: int64

In [41]:
filtrado = df_hr[['education_field', 'job_role']].value_counts().reset_index(name='count')
filtrado

     education_field                   job_role  count
0      life_sciences         research_scientist    129
1          marketing            sales_executive    118
2      life_sciences      laboratory_technician    114
3      life_sciences            sales_executive    101
4            medical         research_scientist     98
5            medical      laboratory_technician     96
6      life_sciences     manufacturing_director     68
7            medical            sales_executive     64
8      life_sciences  healthcare_representative     57
9            medical     manufacturing_director     51
10           medical  healthcare_representative     47
11     life_sciences                    manager     39
12  technical_degree         research_scientist     38
13     life_sciences          research_director     35
14           medical          research_director     32
15           medical                    manager     32
16     life_sciences       sales_representative     27
17             other      laboratory_technician     21
18         marketing       sales_representative     21
19  technical_degree            sales_executive     19
20   human_resources            human_resources     18
21  technical_degree      laboratory_technician     18
22           medical       sales_representative     18
23             other         research_scientist     17
24  technical_degree     manufacturing_director     14
25  technical_degree  healthcare_representative     14
26             other            sales_executive     13
27  technical_degree       sales_representative     13
28         marketing                    manager     13
29     life_sciences            human_resources     12
30           medical            human_resources     11
31             other  healthcare_representative      9
32             other     manufacturing_director      7
33   human_resources                    manager      6
34  technical_degree          research_director      5
35  technical_degree                    manager      5
36             other                    manager      4
37  technical_degree            human_resources      4
38             other            human_resources      3
39             other          research_director      3
40             other       sales_representative      2

In [42]:
df_hr.drop_duplicates(inplace=True)
print(df_hr.duplicated().sum())

0

Gestión datos nulos:

In [43]:
df_hr.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1470 entries, 0 to 1469
Data columns (total 30 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   age                         1397 non-null   Int64
 1   attrition                   1470 non-null   object
 2   business_travel             1353 non-null   object
 3   department                  1441 non-null   object
 4   distance_from_home          1470 non-null   int64
 5   education                   1470 non-null   int64
 6   education_field             1412 non-null   object
 7   employee_number             1470 non-null   int64
 8   environment_satisfaction    1470 non-null   int64
 9   gender                      1470 non-null   object
 10  hourly_rate                 1470 non-null   int64
 11  job_involvement             1470 non-null   int64
 12  job_level                   1470 non-null   int64
 13  job_role                    1470 non-null   object
 14  job_satisfaction            1441 non-null   float64
 15  marital_status              1338 non-null   object
 16  monthly_income              1456 non-null   float64
 17  num_companies_worked        1470 non-null   int64
 18  over_time                   1426 non-null   object
 19  percent_salary_hike         1470 non-null   int64
 20  performance_rating          1470 non-null   int64
 21  relationship_satisfaction   1470 non-null   int64
 22  stock_option_level          1470 non-null   int64
 23  total_working_years         1470 non-null   int64
 24  training_times_last_year    1382 non-null   float64
 25  work_life_balance           1470 non-null   int64
 26  years_at_company            1470 non-null   int64
 27  years_in_current_role       1470 non-null   int64
 28  years_since_last_promotion  1470 non-null   int64
 29  years_with_curr_manager     1323 non-null   float64
dtypes: Int64(1), float64(4), int64(17), object(8)
memory usage: 357.5+ KB

In [44]:
def analisis_descriptivo(df):
    print("🔹 NUMÉRICAS")
    display(df.describe(include = "number").T)
    
    print("\n🔹 CATEGÓRICAS")
    display(df.describe(include="object").T)

In [45]:
df_hr = analisis_descriptivo(df_hr)

🔹 NUMÉRICAS

,count,mean,std,min,25%,50%,75%,max
age,1397.0,36.942734,9.095617,18.0,30.0,36.0,43.0,60.0
distance_from_home,1470.0,9.192517,8.106864,1.0,2.0,7.0,14.0,29.0
education,1470.0,2.912925,1.024165,1.0,2.0,3.0,4.0,5.0
employee_number,1470.0,1024.865306,602.024335,1.0,491.25,1020.5,1555.75,2068.0
environment_satisfaction,1470.0,2.721769,1.093082,1.0,2.0,3.0,4.0,4.0
hourly_rate,1470.0,65.891156,20.329428,30.0,48.0,66.0,83.75,100.0
job_involvement,1470.0,2.729932,0.711561,1.0,2.0,3.0,3.0,4.0
job_level,1470.0,2.063946,1.10694,1.0,1.0,2.0,3.0,5.0
job_satisfaction,1441.0,2.73213,1.105103,1.0,2.0,3.0,4.0,4.0
monthly_income,1456.0,6498.683379,4709.394593,1009.0,2909.0,4907.0,8353.5,19999.0
num_companies_worked,1470.0,2.693197,2.498009,0.0,1.0,2.0,4.0,9.0
percent_salary_hike,1470.0,15.209524,3.659938,11.0,12.0,14.0,18.0,25.0
performance_rating,1470.0,3.153741,0.360824,3.0,3.0,3.0,3.0,4.0
relationship_satisfaction,1470.0,2.712245,1.081209,1.0,2.0,3.0,4.0,4.0
stock_option_level,1470.0,0.793878,0.852077,0.0,0.0,1.0,1.0,3.0
total_working_years,1470.0,11.279592,7.780782,0.0,6.0,10.0,15.0,40.0
training_times_last_year,1382.0,2.798119,1.297989,0.0,2.0,3.0,3.0,6.0
work_life_balance,1470.0,2.761224,0.706476,1.0,2.0,3.0,3.0,4.0
years_at_company,1470.0,7.008163,6.126525,0.0,3.0,5.0,9.0,40.0
years_in_current_role,1470.0,4.229252,3.623137,0.0,2.0,3.0,7.0,18.0
years_since_last_promotion,1470.0,2.187755,3.22243,0.0,0.0,1.0,3.0,15.0
years_with_curr_manager,1323.0,4.068783,3.517918,0.0,2.0,3.0,7.0,17.0

🔹 CATEGÓRICAS

                count unique                     top  freq
attrition        1470      2                      No  1233
business_travel  1353      3                  rarely   951
department       1441      3  research_&_development   939
education_field  1412      6           life_sciences   581
gender           1470      2                    Male   882
job_role         1470      9         sales_executive   326
marital_status   1338      3                 married   606
over_time        1426      2                      No  1021

In [ ]:
print(df_hr.isnull().sum())

age                            73
attrition                       0
business_travel               117
department                     29
distance_from_home              0
education                       0
education_field                58
employee_number                 0
environment_satisfaction        0
gender                          0
hourly_rate                     0
job_involvement                 0
job_level                       0
job_role                        0
job_satisfaction               29
marital_status                132
monthly_income                 14
num_companies_worked            0
over_time                      44
percent_salary_hike             0
performance_rating              0
relationship_satisfaction       0
stock_option_level              0
total_working_years             0
training_times_last_year       88
work_life_balance               0
years_at_company                0
years_in_current_role           0
years_since_last_promotion      0
years_with_curr_manager       147
dtype: int64

In [ ]:
nulos_hr = (df_hr.isnull().mean() * 100)

# Filtrar solo columnas con nulos
nulos_hr = nulos_hr[nulos_hr > 0]

# Convertir a dataframe
nulos_hr = nulos_hr.reset_index()

nulos_hr.rename(columns={"index": "nombre_columna", 0: "%_nulos"}, inplace=True)
nulos_hr["%_nulos"] = nulos_hr["%_nulos"].round(2)

nulos_hr

             nombre_columna  %_nulos
0                       age     4.97
1           business_travel     7.96
2                department     1.97
3           education_field     3.95
4          job_satisfaction     1.97
5            marital_status     8.98
6            monthly_income     0.95
7                 over_time     2.99
8  training_times_last_year     5.99
9   years_with_curr_manager    10.00

In [ ]:
nulos_hr.agg({"%_nulos": ["median", "mean"]})

        %_nulos
median    4.460
mean      4.973

In [ ]:
mediana_nulos = nulos_hr["%_nulos"].median()

nulos_hr["%_nulos"] = nulos_hr["%_nulos"].fillna(mediana_nulos)

In [ ]:
nulos_hr.isnull().sum()

nombre_columna    0
%_nulos           0
dtype: int64

In [ ]:
# Filtrado de empleados que han dejado la empresa (attrition = Yes)
mascara_attrition_yes = df_hr['attrition'] == 'Yes'
df_hr_attrition_yes = df_hr[mascara_attrition_yes]
df_hr_attrition_yes.head(2)

,age,attrition,business_travel,department,distance_from_home,education,education_field,employee_number,environment_satisfaction,gender,hourly_rate,job_involvement,job_level,job_role,job_satisfaction,marital_status,monthly_income,num_companies_worked,over_time,percent_salary_hike,performance_rating,relationship_satisfaction,stock_option_level,total_working_years,training_times_last_year,work_life_balance,years_at_company,years_in_current_role,years_since_last_promotion,years_with_curr_manager
0,41,Yes,rarely,sales,1,2,life_sciences,1,2,Female,94,3,2,sales_executive,4.0,single,5993.0,8,Yes,11,3,1,0,8,0.0,1,6,4,0,5.0
2,37,Yes,rarely,research_&_development,2,2,other,4,4,Male,92,2,1,laboratory_technician,3.0,single,2090.0,6,Yes,15,3,2,0,7,3.0,3,0,0,0,0.0

In [ ]:
# Filtrado de empleados que siguen en la empresa (attrition = No)
mascara_attrition_no = df_hr['attrition'] == 'No'
df_hr_attrition_no = df_hr[mascara_attrition_no]
df_hr_attrition_no.head(2)

,age,attrition,business_travel,department,distance_from_home,education,education_field,employee_number,environment_satisfaction,gender,hourly_rate,job_involvement,job_level,job_role,job_satisfaction,marital_status,monthly_income,num_companies_worked,over_time,percent_salary_hike,performance_rating,relationship_satisfaction,stock_option_level,total_working_years,training_times_last_year,work_life_balance,years_at_company,years_in_current_role,years_since_last_promotion,years_with_curr_manager
1,49,No,frequently,research_&_development,8,1,life_sciences,2,3,Male,61,2,2,research_scientist,2.0,married,5130.0,1,No,23,4,4,1,10,3.0,3,10,7,1,7.0
3,33,No,frequently,research_&_development,3,4,life_sciences,5,4,Female,56,3,1,research_scientist,3.0,married,2909.0,1,Yes,11,3,3,0,8,3.0,3,8,7,3,0.0

In [ ]:
# Guardamos el DataFrame limpio en un nuevo archivo CSV con Attrition = Yes
df_hr.to_csv("df_hr_limpio.csv", index=False)
df_hr_attrition_yes.to_csv("df_hr_attrition_yes.csv", index=False)
df_hr_attrition_no.to_csv("df_hr_attrition_no.csv", index=False)

**<u>revision para limpieza</u>**


**<u>hecho:</u>**

- nombre de columnas en minuscula y separado con _ ✔️
- edad cambiar a int ✔️ 
- job role: cambiar a todo en minusculas ✔️ 
- bussines travel lo dejaria solo con rarely o con frequantly. (quitar travel).✔️ 
- departament: poner en minusculas ✔️ 
- marital status hay singled, maried, divorced, escribir homogeneo ✔️
- eliminar columna employee count ✔️
- education_field categorias en minuscula y separado con _ ✔️
- eliminar duplicados ✔️
- ver cuantos nulos tenemos ✔️




**<u>falta:</u>**
- gestion de nulos ✔️



**<u>Eliminamos columnas:</u>**

- 'employee_count', 'over_18', 'standard_hours', 'monthly_rate', 'daily_rate'✔️
- education field La dejamos ✔️