In [161]:
# Importamos las librerías necesarias
import pandas as pd
import numpy as np
pd.set_option("display.max_columns", None)
import seaborn as sns
import matplotlib.pyplot as plt

In [162]:
# Para imputación de nulos usando métodos estadísticos avanzados
from sklearn.impute import SimpleImputer 
from sklearn.experimental import enable_iterative_imputer # Necesario para IterativeImputer
from sklearn.impute import IterativeImputer 
from sklearn.impute import KNNImputer

In [163]:
df_hr = pd.read_csv("hr.csv")
df_hr.head(2)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41.0,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,sALES eXECUTIVE,4.0,Single,5993.0,19479,8,Y,Yes,11,3,1,80.0,0,8,0.0,1,6,4,0,5.0
1,49.0,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,3,Male,61,2,2,rESEARCH sCIENTIST,2.0,Married,5130.0,24907,1,Y,No,23,4,4,NaN,1,10,3.0,3,10,7,1,7.0

In [164]:
def exploracion_basica(df):
    print(f"Las dos primeras filas son:")
    display(df.head(2))
    print("=" * 50)
    print(f"Las dos últimas filas son:")
    display(df.tail(2))
    print("=" * 50)
    print(f"Las dos filas aleatorias son:")
    display(df.sample(2)) 
    print("=" * 50)
    print(f"Información sobre DataFrame:")
    print(df.info())
    print("=" * 50)
    print(f"El dataframe tiene {df.shape[0]} filas y {df.shape[1]} columnas.")
    return df

In [165]:
df_hr = exploracion_basica(df_hr)

Las dos primeras filas son:

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41.0,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,sALES eXECUTIVE,4.0,Single,5993.0,19479,8,Y,Yes,11,3,1,80.0,0,8,0.0,1,6,4,0,5.0
1,49.0,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,3,Male,61,2,2,rESEARCH sCIENTIST,2.0,Married,5130.0,24907,1,Y,No,23,4,4,NaN,1,10,3.0,3,10,7,1,7.0

==================================================
Las dos últimas filas son:

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
1472,24.0,Yes,Travel_Rarely,240,Human Resources,22,1,Human Resources,1,1714,4,Male,58,1,1,hUMAN rESOURCES,3.0,Married,1555.0,11585,1,Y,No,11,3,3,80.0,1,1,2.0,3,1,0,0,0.0
1473,45.0,No,Travel_Rarely,1339,Research & Development,7,3,Life Sciences,1,86,2,Male,59,3,3,rESEARCH sCIENTIST,1.0,Divorced,9724.0,18787,2,Y,No,17,3,3,NaN,1,25,2.0,3,1,0,0,0.0

==================================================
Las dos filas aleatorias son:

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
1118,26.0,No,NaN,474,Research & Development,3,3,Life Sciences,1,1581,1,Female,89,3,1,rESEARCH sCIENTIST,4.0,NaN,2061.0,11133,1,Y,No,21,4,1,80.0,0,1,5.0,3,1,0,0,0.0
537,27.0,No,Travel_Frequently,294,Research & Development,10,2,Life Sciences,1,733,4,Male,32,3,3,mANUFACTURING dIRECTOR,1.0,Divorced,8793.0,4809,1,Y,No,21,4,3,80.0,2,9,4.0,2,9,7,1,7.0

==================================================
Información sobre DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1474 entries, 0 to 1473
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1401 non-null   float64
 1   Attrition                 1474 non-null   object
 2   BusinessTravel            1357 non-null   object
 3   DailyRate                 1474 non-null   int64
 4   Department                1445 non-null   object
 5   DistanceFromHome          1474 non-null   int64
 6   Education                 1474 non-null   int64
 7   EducationField            1416 non-null   object
 8   EmployeeCount             1474 non-null   int64
 9   EmployeeNumber            1474 non-null   int64
 10  EnvironmentSatisfaction   1474 non-null   int64
 11  Gender                    1474 non-null   object
 12  HourlyRate                1474 non-null   int64
 13  JobInvolvement            1474 non-null   int64
 14  JobLevel                  1474 non-null   int64
 15  JobRole                   1474 non-null   object
 16  JobSatisfaction           1445 non-null   float64
 17  MaritalStatus             1342 non-null   object
 18  MonthlyIncome             1460 non-null   float64
 19  MonthlyRate               1474 non-null   int64
 20  NumCompaniesWorked        1474 non-null   int64
 21  Over18                    1474 non-null   object
 22  OverTime                  1430 non-null   object
 23  PercentSalaryHike         1474 non-null   int64
 24  PerformanceRating         1474 non-null   int64
 25  RelationshipSatisfaction  1474 non-null   int64
 26  StandardHours             1310 non-null   float64
 27  StockOptionLevel          1474 non-null   int64
 28  TotalWorkingYears         1474 non-null   int64
 29  TrainingTimesLastYear     1386 non-null   float64
 30  WorkLifeBalance           1474 non-null   int64
 31  YearsAtCompany            1474 non-null   int64
 32  YearsInCurrentRole        1474 non-null   int64
 33  YearsSinceLastPromotion   1474 non-null   int64
 34  YearsWithCurrManager      1326 non-null   float64
dtypes: float64(6), int64(20), object(9)
memory usage: 403.2+ KB
None
==================================================
El dataframe tiene 1474 filas y 35 columnas.

In [166]:
df_hr.sample(2)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
614,NaN,Yes,Travel_Frequently,887,Research & Development,5,2,Medical,1,848,3,Female,88,2,1,rESEARCH sCIENTIST,3.0,Married,2366.0,20898,1,Y,Yes,14,3,1,80.0,1,8,2.0,3,8,7,1,7.0
417,40.0,No,Travel_Rarely,1398,Sales,2,4,Life Sciences,1,558,3,Female,79,3,5,mANAGER,3.0,Married,18041.0,13022,0,Y,No,14,3,4,80.0,0,21,2.0,3,20,15,1,NaN

In [167]:
# añadir _ a los nombres de las columnas y poner en minúscula

df_hr.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [168]:
import re  #importar regex para insertar guines bajsos antes de mayúsculas internas. Buena práctica
#r'(?<!^)(?=[A-Z])' significa “encuentra cada mayúscula que no esté al inicio, y pon un _ antes”.


df_hr.columns = (
    df_hr.columns
    # 1. Inserta _ entre minúscula y Mayúscula (ej. MonthlyIncome -> Monthly_Income)
    .str.replace(r'([a-z])([A-Z])', r'\1_\2', regex=True)
    # 2. Inserta _ entre una letra y el primer número que encuentre (ej. Over18 -> Over_18)
    .str.replace(r'([a-zA-Z])([0-9])', r'\1_\2', regex=True)
    # 3. Convierte todo a minúsculas
    .str.lower()
)

In [169]:
df_hr.rename(columns={'over18': 'over_18'}, inplace=True)
df_hr.head(2)

,age,attrition,business_travel,daily_rate,department,distance_from_home,education,education_field,employee_count,employee_number,environment_satisfaction,gender,hourly_rate,job_involvement,job_level,job_role,job_satisfaction,marital_status,monthly_income,monthly_rate,num_companies_worked,over_18,over_time,percent_salary_hike,performance_rating,relationship_satisfaction,standard_hours,stock_option_level,total_working_years,training_times_last_year,work_life_balance,years_at_company,years_in_current_role,years_since_last_promotion,years_with_curr_manager
0,41.0,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,sALES eXECUTIVE,4.0,Single,5993.0,19479,8,Y,Yes,11,3,1,80.0,0,8,0.0,1,6,4,0,5.0
1,49.0,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,3,Male,61,2,2,rESEARCH sCIENTIST,2.0,Married,5130.0,24907,1,Y,No,23,4,4,NaN,1,10,3.0,3,10,7,1,7.0

In [170]:
# cambair edad a int

columna_edad_a_int = ['age']

for col in columna_edad_a_int:
    df_hr[col] = df_hr[col].astype('Int64')

df_hr[columna_edad_a_int].dtypes

age    Int64
dtype: object

In [171]:
df_hr['job_role'].unique()

array([' sALES eXECUTIVE ', ' rESEARCH sCIENTIST ',
       ' lABORATORY tECHNICIAN ', ' mANUFACTURING dIRECTOR ',
       ' hEALTHCARE rEPRESENTATIVE ', ' mANAGER ',
       ' sALES rEPRESENTATIVE ', ' rESEARCH dIRECTOR ',
       ' hUMAN rESOURCES '], dtype=object)

In [172]:
df_hr['job_role'] = df_hr['job_role'].str.strip().str.lower().str.replace(r'\s+', '_', regex=True)
df_hr.head(2)

,age,attrition,business_travel,daily_rate,department,distance_from_home,education,education_field,employee_count,employee_number,environment_satisfaction,gender,hourly_rate,job_involvement,job_level,job_role,job_satisfaction,marital_status,monthly_income,monthly_rate,num_companies_worked,over_18,over_time,percent_salary_hike,performance_rating,relationship_satisfaction,standard_hours,stock_option_level,total_working_years,training_times_last_year,work_life_balance,years_at_company,years_in_current_role,years_since_last_promotion,years_with_curr_manager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,sales_executive,4.0,Single,5993.0,19479,8,Y,Yes,11,3,1,80.0,0,8,0.0,1,6,4,0,5.0
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,3,Male,61,2,2,research_scientist,2.0,Married,5130.0,24907,1,Y,No,23,4,4,NaN,1,10,3.0,3,10,7,1,7.0

In [173]:
df_hr['business_travel'].unique()

array(['Travel_Rarely', 'Travel_Frequently', 'Non-Travel', nan],
      dtype=object)

In [174]:
df_hr['business_travel'].value_counts(dropna=False)

business_travel
Travel_Rarely        955
Travel_Frequently    263
Non-Travel           139
NaN                  117
Name: count, dtype: int64

In [175]:
# 1. cambiar nombre de categorias: 

nuevas_categorias_business_travel = {
    'Travel_Rarely': 'rarely',
    'Travel_Frequently': 'frequently',
    'Non-Travel': 'non_travel'}

In [176]:
# aplicar el reemplazo
df_hr['business_travel'] = df_hr['business_travel'].replace(nuevas_categorias_business_travel)

In [177]:
# comprobar

df_hr.head(2)

,age,attrition,business_travel,daily_rate,department,distance_from_home,education,education_field,employee_count,employee_number,environment_satisfaction,gender,hourly_rate,job_involvement,job_level,job_role,job_satisfaction,marital_status,monthly_income,monthly_rate,num_companies_worked,over_18,over_time,percent_salary_hike,performance_rating,relationship_satisfaction,standard_hours,stock_option_level,total_working_years,training_times_last_year,work_life_balance,years_at_company,years_in_current_role,years_since_last_promotion,years_with_curr_manager
0,41,Yes,rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,sales_executive,4.0,Single,5993.0,19479,8,Y,Yes,11,3,1,80.0,0,8,0.0,1,6,4,0,5.0
1,49,No,frequently,279,Research & Development,8,1,Life Sciences,1,2,3,Male,61,2,2,research_scientist,2.0,Married,5130.0,24907,1,Y,No,23,4,4,NaN,1,10,3.0,3,10,7,1,7.0

In [178]:
df_hr['department'].unique()

array(['Sales', 'Research & Development', nan, 'Human Resources'],
      dtype=object)

In [179]:
df_hr['department'] = df_hr['department'].str.strip().str.lower().str.replace(r'\s+', '_', regex=True)

In [180]:
df_hr['department'].unique()

array(['sales', 'research_&_development', nan, 'human_resources'],
      dtype=object)

In [181]:
df_hr['marital_status'].unique()

array(['Single', 'Married', 'Divorced', nan, 'Marreid'], dtype=object)

In [182]:
df_hr['marital_status'] = df_hr['marital_status'].str.strip().str.lower().str.replace(r'\s+', '_', regex=True)

In [183]:
df_hr['marital_status'].unique()

array(['single', 'married', 'divorced', nan, 'marreid'], dtype=object)

In [184]:
nuevas_categorias_marital_status = {
    'single': 'single',
    'married': 'married',
    'divorced': 'divorced',
    'marreid': 'married'
    }

In [185]:
# aplicar el reemplazo
df_hr['marital_status'] = df_hr['marital_status'].replace(nuevas_categorias_marital_status)

In [186]:
df_hr.sample(5)

,age,attrition,business_travel,daily_rate,department,distance_from_home,education,education_field,employee_count,employee_number,environment_satisfaction,gender,hourly_rate,job_involvement,job_level,job_role,job_satisfaction,marital_status,monthly_income,monthly_rate,num_companies_worked,over_18,over_time,percent_salary_hike,performance_rating,relationship_satisfaction,standard_hours,stock_option_level,total_working_years,training_times_last_year,work_life_balance,years_at_company,years_in_current_role,years_since_last_promotion,years_with_curr_manager
826,38,No,rarely,433,human_resources,1,3,Human Resources,1,1152,3,Male,37,4,1,human_resources,3.0,married,2844.0,6004,1,Y,No,13,3,4,80.0,1,7,2.0,4,7,6,5,0.0
1129,42,No,rarely,1059,research_&_development,9,2,Other,1,1595,4,Male,93,2,5,manager,4.0,single,19613.0,26362,8,Y,No,22,4,4,80.0,0,24,2.0,3,1,0,0,1.0
1009,58,No,rarely,1055,research_&_development,1,3,Medical,1,1423,4,Female,76,3,5,research_director,1.0,married,19701.0,22456,3,Y,Yes,21,4,3,80.0,1,32,3.0,3,9,8,1,5.0
447,35,No,rarely,619,sales,1,3,Marketing,1,600,2,Male,85,3,2,sales_executive,3.0,married,4717.0,18659,9,Y,No,11,3,3,80.0,0,15,2.0,3,11,9,6,9.0
969,48,No,NaN,855,research_&_development,4,3,Life Sciences,1,1363,4,Male,54,3,3,manufacturing_director,4.0,single,7898.0,18706,1,Y,No,11,3,3,80.0,0,11,2.0,3,10,9,0,8.0

In [187]:
df_hr.dtypes

age                             Int64
attrition                      object
business_travel                object
daily_rate                      int64
department                     object
distance_from_home              int64
education                       int64
education_field                object
employee_count                  int64
employee_number                 int64
environment_satisfaction        int64
gender                         object
hourly_rate                     int64
job_involvement                 int64
job_level                       int64
job_role                       object
job_satisfaction              float64
marital_status                 object
monthly_income                float64
monthly_rate                    int64
num_companies_worked            int64
over_18                        object
over_time                      object
percent_salary_hike             int64
performance_rating              int64
relationship_satisfaction       int64
standard_hours                float64
stock_option_level              int64
total_working_years             int64
training_times_last_year      float64
work_life_balance               int64
years_at_company                int64
years_in_current_role           int64
years_since_last_promotion      int64
years_with_curr_manager       float64
dtype: object

In [188]:
df_hr['education_field'].unique()

array(['Life Sciences', 'Other', 'Medical', nan, 'Marketing',
       'Technical Degree', 'Human Resources'], dtype=object)

In [189]:
df_hr['education_field'] = df_hr['education_field'].str.strip().str.lower().str.replace(r'\s+', '_', regex=True)

In [190]:
df_hr['education_field'].unique()

array(['life_sciences', 'other', 'medical', nan, 'marketing',
       'technical_degree', 'human_resources'], dtype=object)

In [191]:
df_hr.columns

Index(['age', 'attrition', 'business_travel', 'daily_rate', 'department',
       'distance_from_home', 'education', 'education_field', 'employee_count',
       'employee_number', 'environment_satisfaction', 'gender', 'hourly_rate',
       'job_involvement', 'job_level', 'job_role', 'job_satisfaction',
       'marital_status', 'monthly_income', 'monthly_rate',
       'num_companies_worked', 'over_18', 'over_time', 'percent_salary_hike',
       'performance_rating', 'relationship_satisfaction', 'standard_hours',
       'stock_option_level', 'total_working_years', 'training_times_last_year',
       'work_life_balance', 'years_at_company', 'years_in_current_role',
       'years_since_last_promotion', 'years_with_curr_manager'],
      dtype='object')

In [192]:
df_hr['standard_hours'].unique()

array([80., nan])

In [193]:
df_hr['over_18'].unique()

array(['Y'], dtype=object)

In [194]:
# Eliminamos columnas que no aportan información relevante para el análisis o modelado
df_hr = df_hr.drop(columns=['employee_count', 'over_18', 'standard_hours', 'monthly_rate', 'daily_rate'], errors='ignore')

In [195]:
df_hr.head(2)

,age,attrition,business_travel,department,distance_from_home,education,education_field,employee_number,environment_satisfaction,gender,hourly_rate,job_involvement,job_level,job_role,job_satisfaction,marital_status,monthly_income,num_companies_worked,over_time,percent_salary_hike,performance_rating,relationship_satisfaction,stock_option_level,total_working_years,training_times_last_year,work_life_balance,years_at_company,years_in_current_role,years_since_last_promotion,years_with_curr_manager
0,41,Yes,rarely,sales,1,2,life_sciences,1,2,Female,94,3,2,sales_executive,4.0,single,5993.0,8,Yes,11,3,1,0,8,0.0,1,6,4,0,5.0
1,49,No,frequently,research_&_development,8,1,life_sciences,2,3,Male,61,2,2,research_scientist,2.0,married,5130.0,1,No,23,4,4,1,10,3.0,3,10,7,1,7.0

In [196]:
df_hr['gender'].unique()

array(['Female', 'Male'], dtype=object)

In [197]:
print(df_hr.duplicated().sum())

4

In [198]:
mascara_duplicados_hr = df_hr.duplicated(keep=False)
mascara_duplicados_hr

0       False
1       False
2       False
3       False
4       False
        ...
1469    False
1470     True
1471     True
1472     True
1473     True
Length: 1474, dtype: bool

In [199]:
df_hr[mascara_duplicados_hr].sort_values(by="employee_number")

,age,attrition,business_travel,department,distance_from_home,education,education_field,employee_number,environment_satisfaction,gender,hourly_rate,job_involvement,job_level,job_role,job_satisfaction,marital_status,monthly_income,num_companies_worked,over_time,percent_salary_hike,performance_rating,relationship_satisfaction,stock_option_level,total_working_years,training_times_last_year,work_life_balance,years_at_company,years_in_current_role,years_since_last_promotion,years_with_curr_manager
67,45,No,rarely,research_&_development,7,3,life_sciences,86,2,Male,59,3,3,research_scientist,1.0,divorced,9724.0,2,No,17,3,3,1,25,2.0,3,1,0,0,0.0
1473,45,No,rarely,research_&_development,7,3,life_sciences,86,2,Male,59,3,3,research_scientist,1.0,divorced,9724.0,2,No,17,3,3,1,25,2.0,3,1,0,0,0.0
1471,53,No,rarely,research_&_development,13,2,medical,250,4,Female,57,4,2,manufacturing_director,1.0,divorced,4450.0,1,No,11,3,3,2,5,3.0,3,4,2,1,3.0
184,53,No,rarely,research_&_development,13,2,medical,250,4,Female,57,4,2,manufacturing_director,1.0,divorced,4450.0,1,No,11,3,3,2,5,3.0,3,4,2,1,3.0
1470,28,No,rarely,sales,5,3,medical,1469,4,Male,84,3,2,sales_executive,1.0,single,8463.0,0,No,18,3,4,0,6,4.0,3,5,4,1,NaN
1041,28,No,rarely,sales,5,3,medical,1469,4,Male,84,3,2,sales_executive,1.0,single,8463.0,0,No,18,3,4,0,6,4.0,3,5,4,1,NaN
1222,24,Yes,rarely,human_resources,22,1,human_resources,1714,4,Male,58,1,1,human_resources,3.0,married,1555.0,1,No,11,3,3,1,1,2.0,3,1,0,0,0.0
1472,24,Yes,rarely,human_resources,22,1,human_resources,1714,4,Male,58,1,1,human_resources,3.0,married,1555.0,1,No,11,3,3,1,1,2.0,3,1,0,0,0.0

In [200]:
df_hr['attrition'].value_counts()

attrition
No     1236
Yes     238
Name: count, dtype: int64

In [201]:
filtrado = df_hr[['education_field', 'job_role']].value_counts().reset_index(name='count')
filtrado

     education_field                   job_role  count
0      life_sciences         research_scientist    129
1          marketing            sales_executive    118
2      life_sciences      laboratory_technician    114
3      life_sciences            sales_executive    101
4            medical         research_scientist     98
5            medical      laboratory_technician     96
6      life_sciences     manufacturing_director     68
7            medical            sales_executive     64
8      life_sciences  healthcare_representative     57
9            medical     manufacturing_director     51
10           medical  healthcare_representative     47
11     life_sciences                    manager     39
12  technical_degree         research_scientist     38
13     life_sciences          research_director     35
14           medical          research_director     32
15           medical                    manager     32
16     life_sciences       sales_representative     27
17             other      laboratory_technician     21
18         marketing       sales_representative     21
19  technical_degree            sales_executive     19
20   human_resources            human_resources     18
21  technical_degree      laboratory_technician     18
22           medical       sales_representative     18
23             other         research_scientist     17
24  technical_degree     manufacturing_director     14
25  technical_degree  healthcare_representative     14
26             other            sales_executive     13
27  technical_degree       sales_representative     13
28         marketing                    manager     13
29     life_sciences            human_resources     12
30           medical            human_resources     11
31             other  healthcare_representative      9
32             other     manufacturing_director      7
33   human_resources                    manager      6
34  technical_degree          research_director      5
35  technical_degree                    manager      5
36             other                    manager      4
37  technical_degree            human_resources      4
38             other            human_resources      3
39             other          research_director      3
40             other       sales_representative      2

In [202]:
df_hr.drop_duplicates(inplace=True)
print(df_hr.duplicated().sum())

0

In [203]:
print(df_hr.isnull().sum())

age                            73
attrition                       0
business_travel               117
department                     29
distance_from_home              0
education                       0
education_field                58
employee_number                 0
environment_satisfaction        0
gender                          0
hourly_rate                     0
job_involvement                 0
job_level                       0
job_role                        0
job_satisfaction               29
marital_status                132
monthly_income                 14
num_companies_worked            0
over_time                      44
percent_salary_hike             0
performance_rating              0
relationship_satisfaction       0
stock_option_level              0
total_working_years             0
training_times_last_year       88
work_life_balance               0
years_at_company                0
years_in_current_role           0
years_since_last_promotion      0
years_with_curr_manager       147
dtype: int64

In [215]:
nulos_hr = (df_hr.isnull().mean() * 100)

# Filtrar solo columnas con nulos
nulos_hr = nulos_hr[nulos_hr > 0]

# Convertir a dataframe
nulos_hr = nulos_hr.reset_index()

nulos_hr.rename(columns={"index": "nombre_columna", 0: "%_nulos"}, inplace=True)
nulos_hr["%_nulos"] = nulos_hr["%_nulos"].round(2)

nulos_hr

             nombre_columna  %_nulos
0                       age     4.97
1           business_travel     7.96
2                department     1.97
3           education_field     3.95
4          job_satisfaction     1.97
5            marital_status     8.98
6            monthly_income     0.95
7                 over_time     2.99
8  training_times_last_year     5.99
9   years_with_curr_manager    10.00

In [212]:
nulos_hr.agg({"%_nulos": ["median", "mean"]})

        %_nulos
median    4.460
mean      4.973

In [213]:
mediana_nulos = nulos_hr["%_nulos"].median()

nulos_hr["%_nulos"] = nulos_hr["%_nulos"].fillna(mediana_nulos)

In [214]:
nulos_hr.isnull().sum()

nombre_columna    0
%_nulos           0
dtype: int64

In [218]:
# Filtrado de empleados que han dejado la empresa (attrition = Yes)
mascara_attrition_yes = df_hr['attrition'] == 'Yes'
df_hr_attrition_yes = df_hr[mascara_attrition_yes]
df_hr_attrition_yes.head(2)

,age,attrition,business_travel,department,distance_from_home,education,education_field,employee_number,environment_satisfaction,gender,hourly_rate,job_involvement,job_level,job_role,job_satisfaction,marital_status,monthly_income,num_companies_worked,over_time,percent_salary_hike,performance_rating,relationship_satisfaction,stock_option_level,total_working_years,training_times_last_year,work_life_balance,years_at_company,years_in_current_role,years_since_last_promotion,years_with_curr_manager
0,41,Yes,rarely,sales,1,2,life_sciences,1,2,Female,94,3,2,sales_executive,4.0,single,5993.0,8,Yes,11,3,1,0,8,0.0,1,6,4,0,5.0
2,37,Yes,rarely,research_&_development,2,2,other,4,4,Male,92,2,1,laboratory_technician,3.0,single,2090.0,6,Yes,15,3,2,0,7,3.0,3,0,0,0,0.0

In [220]:
# Filtrado de empleados que siguen en la empresa (attrition = No)
mascara_attrition_no = df_hr['attrition'] == 'No'
df_hr_attrition_no = df_hr[mascara_attrition_no]
df_hr_attrition_no.head(2)

,age,attrition,business_travel,department,distance_from_home,education,education_field,employee_number,environment_satisfaction,gender,hourly_rate,job_involvement,job_level,job_role,job_satisfaction,marital_status,monthly_income,num_companies_worked,over_time,percent_salary_hike,performance_rating,relationship_satisfaction,stock_option_level,total_working_years,training_times_last_year,work_life_balance,years_at_company,years_in_current_role,years_since_last_promotion,years_with_curr_manager
1,49,No,frequently,research_&_development,8,1,life_sciences,2,3,Male,61,2,2,research_scientist,2.0,married,5130.0,1,No,23,4,4,1,10,3.0,3,10,7,1,7.0
3,33,No,frequently,research_&_development,3,4,life_sciences,5,4,Female,56,3,1,research_scientist,3.0,married,2909.0,1,Yes,11,3,3,0,8,3.0,3,8,7,3,0.0

In [221]:
# Guardamos el DataFrame limpio en un nuevo archivo CSV con Attrition = Yes
df_hr.to_csv("df_hr_limpio.csv", index=False)
df_hr_attrition_yes.to_csv("df_hr_attrition_yes.csv", index=False)
df_hr_attrition_no.to_csv("df_hr_attrition_no.csv", index=False)

**<u>revision para limpieza</u>**


**<u>hecho:</u>**

- nombre de columnas en minuscula y separado con _ ✔️
- edad cambiar a int ✔️ 
- job role: cambiar a todo en minusculas ✔️ 
- bussines travel lo dejaria solo con rarely o con frequantly. (quitar travel).✔️ 
- departament: poner en minusculas ✔️ 
- marital status hay singled, maried, divorced, escribir homogeneo ✔️
- eliminar columna employee count ✔️
- education_field categorias en minuscula y separado con _ ✔️
- eliminar duplicados ✔️
- ver cuantos nulos tenemos ✔️




**<u>falta:</u>**
- gestion de nulos ✔️



**<u>Eliminamos columnas:</u>**

- 'employee_count', 'over_18', 'standard_hours', 'monthly_rate', 'daily_rate'✔️
- education field La dejamos ✔️